apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.insecureRepository: 'true'
  generation: 4
  name: js-console
spec:
  dockerImageRepository: quay.io/sshaaf/js-console
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/sshaaf/js-console:latest'
      generation: 4
      importPolicy:
        insecure: true
      name: latest
      referencePolicy:
        type: Source
